#!/bin/bash
mainpath=$PWD
       echo -n "
Roman   - R
Build   - B
Prepare - P
System  - S

"
if [ "$mainpath" = /home/$USER ]
then
echo " Please change directory to working directory. "
exit 0
else
echo "Working directory: "$mainpath"/
"
fi
echo -n "
Select action: 

mk) Build a ROM

u) Update script

s) Download tree & vendor 

k) Download kernel

p) Patch ROM (LOS based) for work on MT6572 (kernel 3.4.67)  
      
los) Download LOS 14.1 to your folder

Your choose: "

read item
case "$item" in
    los|LOS) read -r -p "Are you sure? [y/N] " response
case "$response" in
    [yY][eE][sS]|[yY]) 
        ;;
    *)
        echo "Download canceled."
        exit 0
        ;;
esac
    echo "Starting"
rm -rf $mainpath
cd $mainpath && repo init -u git://github.com/LineageOS/android.git -b cm-14.1
cd $mainpath && repo sync
echo "Done"
exit 0
        ;;
    s|S) 
  echo -n "RBPS -
Roman
Build
Prepare
System

Working directory: $mainpath/

Select device:

1) Lenovo A369i (LOLIPOP)

2) Lenovo A369i (KitKat)

3) Micromax A102

4) Explay JoyTV

Your choose: "

read item
case "$item" in
    
1) read -r -p "Are you sure? [y/N] " response
case "$response" in
    [yY][eE][sS]|[yY]) 
        ;;
    *)
        echo "Download canceled."
        exit 0
        ;;
esac
echo -n "Downloading"
git clone -q https://github.com/melekpro/Android-Device-Lenovo-A369i-LP $mainpath/device/Lenovo/A369i/
git clone -q https://github.com/melekpro/Android-Vendor-Lenovo-A369i-LP $mainpath/vendor/Lenovo/A369i/
echo -n "Done"
;;
2) read -r -p "Are you sure? [y/N] " response
case "$response" in
    [yY][eE][sS]|[yY]) 
        ;;
    *)
        echo "Download canceled."
        exit 0
        ;;
esac 
echo -n "Downloading\r"
git clone -q https://github.com/Manish4586/android_device_lenovo_a369i $mainpath/device/lenovo/a369i/
git clone -q https://github.com/Manish4586/android_vendor_lenovo_a369i $mainpath/vendor/lenovo/a369i/
echo -ne "Done\r"
;;
3) read -r -p "Are you sure? [y/N] " response
case "$response" in
    [yY][eE][sS]|[yY]) 
        ;;
    *)
        echo "Download canceled."
        exit 0
        ;;
esac
echo -n "Downloading"
git clone -q https://github.com/AndroidDevelopersTeam/android_device_Micromax_A102 $mainpath/device/Micromax/A102/
git clone -q https://github.com/AndroidDevelopersTeam/android_vendor_Micromax_A102 $mainpath/vendor/Micromax/A102/
echo -n "Done"
;;
4) read -r -p "Are you sure? [y/N] " response
case "$response" in
    [yY][eE][sS]|[yY]) 
        ;;
    *)
        echo "Download canceled."
        exit 0
        ;;
esac
echo -n "Downloading"
git clone -q https://github.com/TestMT6572/android_device_Explay_JoyTV $mainpath/device/Explay/JoyTV/
git clone -q https://github.com/TestMT6572/android_vendor_Explay_JoyTV $mainpath/vendor/Explay/JoyTV/
echo -n "Done"
;;
*) echo -n "What u write?"
;;
esac
        ;;

p|P) read -r -p "Are you sure? [y/N] " response
case "$response" in
    [yY][eE][sS]|[yY]) 
        ;;
    *)
        echo "Patching canceled."
        exit 0
        ;;
esac
echo "Removing old folders..."
rm -Rf $mainpath/external/wpa_supplicant_8
echo -ne "8%\r"
rm -Rf $mainpath/frameworks/av
echo -ne "16%\r"
rm -Rf $mainpath/frameworks/base
echo -ne "24%\r"
rm -Rf $mainpath/frameworks/native
echo -ne "32%\r"
rm -Rf $mainpath/frameworks/opt/telephony
echo -ne "40%\r"
rm -Rf $mainpath/packages/apps/Dialer
echo -ne "48%\r"
rm -Rf $mainpath/packages/services/Telephony
echo -ne "56%\r"
rm -Rf $mainpath/system/bt
echo -ne "64%\r"
rm -Rf $mainpath/system/core
echo -ne "72%\r"
rm -Rf $mainpath/system/netd
echo -ne "80%\r"
rm -Rf $mainpath/system/sepolicy
echo -ne "88%\r"
rm -Rf ~$mainpath/vendor/codeaurora/telephony
echo -ne "100%\r"
sleep 1
echo "Trying to patch..."
cp -r ~/android/patches/external/. $mainpath/external/
echo -ne "20%\r"
cp -r ~/android/patches/frameworks/. $mainpath/frameworks/
echo -ne "40%\r"
cp -r ~/android/patches/packages/. $mainpath/packages/
echo -ne "60%\r"
cp -r ~/android/patches/system/. $mainpath/system/
echo -ne "80%\r"
cp -r ~/android/patches/vendor/. $mainpath/vendor
echo -ne "100%\r"
echo "Patched!"
exit 0
;;
mk|MK) 
read -r -p "Are you sure? [y/N] " response
case "$response" in
    [yY][eE][sS]|[yY]) 
        ;;
    *)
        echo "Building canceled."
        exit 0
        ;;
esac
echo "Start build in: /home/$USER/"$1"/"
sleep 1
echo "Enter device name: lineage_"
read device
echo "Enter build type (eng, user, userdebug): "
read type
echo "Device name: "$device", Build type: "$type""
sleep 1
cd $mainpath && . build/envsetup.sh
cd $mainpath && export LC_ALL=C
cd $mainpath && lunch "$device"-"$type"
sleep 1
echo -ne "Write n for disable cache or Write cache space (in Gigabytes): "
read ccache_space
case "$ccache_space" in
    
n|N) echo -ne "Ccache disabled.\r"
;;
*) cd $mainpath && prebuilts/misc/linux-x86/ccache/ccache -M "$ccache_space"G
;;
esac
cd $mainpath && mka bacon
echo "Done"
exit 0
;;
k|K) 
  echo -n "RBPS -
Roman
Build
Prepare
System

Working directory: $mainpath/

Select device:

1) Lenovo A369i (3.4.67)

2) Lenovo A369i (3.10.89)

Your choose: "

read item
case "$item" in
    
1) read -r -p "Are you sure? [y/N] " response
case "$response" in
    [yY][eE][sS]|[yY]) 
        ;;
    *)
        echo "Download canceled."
        exit 0
        ;;
esac
echo -n "Downloading"

echo -n "Done"
;;
2) read -r -p "Are you sure? [y/N] " response
case "$response" in
    [yY][eE][sS]|[yY]) 
        ;;
    *)
        echo "Download canceled."
        exit 0
        ;;
esac 
echo -n "Downloading\r"
git clone -q git@github.com:Manish4586/android_kernel_lenovo_a369i.git $mainpath/kernel/lenovo/a369i/
echo -ne "Done\r"
;;
*) echo -n "What u write?"
;;
esac
        ;;

u|U) echo "Your version:"
cat /home/$USER/bin/prepare/version/version.txt
git clone -q https://github.com/RomanDesigner/script-updater /home/$USER/prepare/tmp/
cd /home/$USER/prepare/tmp/ && chmod +x updateScript && ./updateScript
;;
*) echo "Error 1: command not found"
;;
esac
